services:
  app:
    build:
      context: .    # Utilise le Dockerfile à la racine
    container_name: ter

    # On monte tous les dossiers nécessaires
    volumes:
      - ./Donnees/birds_dataset:/Donnees/birds_dataset
      - ./Donnees/oiseaux_extraits:/Donnees/oiseaux_extraits
      - ./Donnees/backgrounds_extracted:/Donnees/backgrounds_extracted
      - ./Codes:/Codes

    # On s'appuie sur le WORKDIR défini dans le Dockerfile (par défaut /Codes)
    # et on invoque le script avec son chemin relatif
    command: ["pwsh", "./principal.ps1"]

    stdin_open: true
    tty: true
